### ISSUE TITLE
Can't get it to run NPM test and pass

### ISSUE THREAD

**Issue by jbrodley** [jimpick/lambda-comments#12]
Tried to use today and everything worked until I got to the npm run test.  Getting the following error:

1 failing

  1) local Post new comment to the queue should catch spam:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.2.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! lambda-comments@0.0.2 test: `mocha --compilers js:./babel-register`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lambda-comments@0.0.2 test script 'mocha --compilers js:./babel-register'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lambda-comments package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --compilers js:./babel-register
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lambda-comments
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lambda-comments
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jbrodley/lambda-comments/npm-debug.log

from Debug log. 

sxjbrodmbp:lambda-comments jbrodley$ vi /Users/jbrodley/lambda-comments/npm-debug.log 

11 silly lifecycle lambda-comments@0.0.2~test: Args: [ '-c', 'mocha --compilers js:./babel-register' ]
12 silly lifecycle lambda-comments@0.0.2~test: Returned: code: 1  signal: null
13 info lifecycle lambda-comments@0.0.2~test: Failed to exec test script
14 verbose stack Error: lambda-comments@0.0.2 test: `mocha --compilers js:./babel-register`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid lambda-comments@0.0.2
16 verbose cwd /Users/jbrodley/lambda-comments
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "run" "test"
19 error node v6.2.1
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error lambda-comments@0.0.2 test: `mocha --compilers js:./babel-register`
22 error Exit status 1
23 error Failed at the lambda-comments@0.0.2 test script 'mocha --compilers js:./babel-register'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the lambda-comments package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     mocha --compilers js:./babel-register
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs lambda-comments
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls lambda-comments
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jbrodley** [comment]
ahh this is because I didn't enable Akismet.  Adding an API key for Akismet resolved this issue.
