### ISSUE TITLE
'npm start' in packages/frontend fails with Node 6.1.0

### ISSUE THREAD

**Issue by jimpick** [jimpick/lambda-comments#7]
```
$ npm start

> @jimpick/lambda-comments-frontend@1.0.0 start /Users/jim/projects/comments/lambda-comments/packages/frontend
> if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev


> @jimpick/lambda-comments-frontend@1.0.0 react-project:start:dev /Users/jim/projects/comments/lambda-comments/packages/frontend
> eslint src && react-project start

[react-project] [start] task
[react-project] checking app dependencies
[react-project] Some of your dependencies don't match what I expect
[react-project] You have: babel-eslint@6.0.2 and I expect babel-eslint@4.1.8
[react-project] You have: eslint@2.7.0 and I expect eslint@1.10.3
[react-project] You have: eslint-plugin-react@4.3.0 and I expect eslint-plugin-react@3.16.1
[react-project] You have: webpack@1.13.0 and I expect webpack@1.12.14
[react-project] You might want to `npm install` the versions I expect.
[react-project] NODE_ENV=development
/Users/jim/projects/comments/lambda-comments/packages/frontend/node_modules/react-project/lib/build.js:53
    if (err) throw err;
             ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /Users/jim/projects/comments/lambda-comments/packages/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:36
    at /Users/jim/projects/comments/lambda-comments/packages/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/jim/projects/comments/lambda-comments/packages/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:385:20)
    at OptionManager.mergePresets (/Users/jim/projects/comments/lambda-comments/packages/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:10)
```

**Comment by jimpick** [comment]
Works with Node 5.10.1
